---
- hosts: all
  tasks:
    - include_tasks: playbooks/debian_hosts_tasks.yml
      become: true
      become_user: root
      when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "8")
    - include_tasks: playbooks/debian9_hosts_tasks.yml
      become: true
      become_user: root
      when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")
    - include_tasks: playbooks/rhel_hosts_tasks.yml
      become: true
      become_user: root
      when: ((ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat") and ansible_facts['distribution_major_version'] == "7")
    - include_tasks: playbooks/all_hosts_tasks.yml
      become: true
      become_user: root
    - include_tasks: playbooks/debian_hosts_post_tasks.yml
      become: true
      become_user: root
      when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "8")
    - include_tasks: playbooks/debian9_hosts_post_tasks.yml
      become: true
      become_user: root
      when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] == "9")
    - include_tasks: playbooks/rhel_hosts_post_tasks.yml
      become: true
      become_user: root
      when: ((ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat") and ansible_facts['distribution_major_version'] == "7")
    - include_tasks: playbooks/ubuntu18_hosts_tasks.yml
      become: true
      become_user: root
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18")


